config/routes.rb
Rails.application.routes.draw do
  root to: "users#intro"
  get "/intro" => "users#intro"
  get "/game" => "users#game"
    resources :users
    resources :posts
end

app/models/post.rb
class Post < ActiveRecord::Base

	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		@posts = Post.all
	end

	def show
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.create

		if @post.save
			redirect_to @post
		else
			render 'new'
	end
end

	def edit
	end

	def update
		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
	end

	def destroy
		@post.destroy
		redirect_to root_path
	end


	private

	def find_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:title, :content)
end

end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
	end

	def show
	end

	def new
	end

	def intro
	end

	def game
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Juno</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= yield :extra_js %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
</body>
</html>

app/views/posts/_form.html.erb
<div id="form_wrapper"><%= form_for Post.new do |f| %>
<%= f.text_field :title %>
<%= f.text_field :content %>
<%= f.submit %>

<% end %>

</div>

app/views/posts/edit.html.erb
<%= render 'form' %>

<%= link_to 'cancel', post_path %>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<h1>@post.title</h1>
<p>@post.content</p>

<%= link_to "edit", edit_post_path(@post) %>
<%= link_to "delete", post_path(@post), method: :delete, data: {confirm: "Are you sure?"} %>
<%= link_to 'home', root_path %>

app/views/users/game.html.erb
<%= content_for :extra_js do %>
	<%= javascript_include_tag :game %>
<% end %>


<div id="arrow_box">
<img src="assets/arrow_keys.png" height="130" width="210"><br>
<p>Move the kitty with the arrow keys</p>
<img src="assets/spacebar.png" height="50" width="210">
<p>Use Spacebar to fire!</p>
</div>

app/views/users/intro.html.erb
<div id="intro_wrapper">
<h3><%= link_to "Skip Intro", game_path %></h3>
<div id = "titles"><div id="content">

<h2>Juno: A Space Adventure</h2><br><br>


<p>In a galaxy far far away, there is a planet called Cattooine. It is here where the cats write all the rules. 

One day, Juno got the call to go back to the planet she called home. Cattoine was being attacked by the dreaded vaccuums. Vaccuums and cats are mortal enemies, and without help the vacuums will suck up all of planet.
 
After a nice dose of catnip and the perfect open door opportunity, Juno had her escape and was on her way back to Cattoine. And this is her journey. </p>

</div></div>	
</div>

app/views/users/show.html.erb
show.html.erb